language: node_js
os: osx
node_js:
 - "9"

matrix:
  fast_finish: true

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/Library/Caches/electron
    - $HOME/Library/Caches/electron-builder

script:
  - yarn build
